export const maplist = [
  "andhra17.gif",
  "andhra19.gif",
  "andhra23.gif",
  "andhra50.gif",
  "andhra55.gif",
  "arunachal17.gif",
  "arunachal19.gif",
  "arunachal23.gif",
  "arunachal50.gif",
  "arunachal55.gif",
  "assam17.gif",
  "assam19.gif",
  "assam23.gif",
  "assam50.gif",
  "assam55.gif",
  "bengale17.gif",
  "bengale19.gif",
  "bengale23.gif",
  "bengale50.gif",
  "bengale55.gif",
  "bihar17.gif",
  "bihar19.gif",
  "bihar23.gif",
  "bihar50.gif",
  "bihar55.gif",
  "bihar89.gif",
  "chandigarh17.gif",
  "chhattisgarh17.gif",
  "chhattisgarh19.gif",
  "chhattisgarh23.gif",
  "chhattisgarh50.gif",
  "chhattisgarh55.gif",
  "dadra17.gif",
  "dadra19.gif",
  "dadra23.gif",
  "delhi17.gif",
  "delhi19.gif",
  "delhi23.gif",
  "delhi50.gif",
  "delhi55.gif",
  "goa17.gif",
  "goa19.gif",
  "goa23.gif",
  "goa50.gif",
  "goa55.gif",
  "gujarat17.gif",
  "gujarat19.gif",
  "gujarat23.gif",
  "gujarat50.gif",
  "gujarat55.gif",
  "haryana17.gif",
  "haryana19.gif",
  "haryana23.gif",
  "haryana50.gif",
  "haryana55.gif",
  "himachal17.gif",
  "himachal19.gif",
  "himachal23.gif",
  "himachal50.gif",
  "himachal55.gif",
  "jammuandkashmir17.gif",
  "jammuandkashmir19.gif",
  "jammuandkashmir23.gif",
  "jammuandkashmir50.gif",
  "jammuandkashmir55.gif",
  "jammuandkashmir89.gif",
  "jharkhand17.gif",
  "jharkhand19.gif",
  "jharkhand23.gif",
  "jharkhand50.gif",
  "jharkhand55.gif",
  "karaikal17.gif",
  "karaikal19.gif",
  "karaikal23.gif",
  "karaikal50.gif",
  "karnataka17.gif",
  "karnataka19.gif",
  "karnataka23.gif",
  "karnataka50.gif",
  "karnataka55.gif",
  "kerala17.gif",
  "kerala19.gif",
  "kerala23.gif",
  "kerala50.gif",
  "kerala55.gif",
  "ladakh17.gif",
  "ladakh19.gif",
  "ladakh23.gif",
  "ladakh50.gif",
  "ladakh55.gif",
  "madhya17.gif",
  "madhya19.gif",
  "madhya23.gif",
  "madhya50.gif",
  "madhya55.gif",
  "madhya89.gif",
  "maharashtra17.gif",
  "maharashtra19.gif",
  "maharashtra23.gif",
  "maharashtra50.gif",
  "maharashtra55.gif",
  "maharashtra89.gif",
  "mahe17.gif",
  "mahe19.gif",
  "mahe23.gif",
  "mahe50.gif",
  "manipur17.gif",
  "manipur19.gif",
  "manipur23.gif",
  "manipur50.gif",
  "manipur55.gif",
  "meghalaya17.gif",
  "meghalaya19.gif",
  "meghalaya23.gif",
  "meghalaya50.gif",
  "meghalaya55.gif",
  "mizoram17.gif",
  "mizoram19.gif",
  "mizoram23.gif",
  "mizoram50.gif",
  "mizoram55.gif",
  "nagaland17.gif",
  "nagaland19.gif",
  "nagaland23.gif",
  "nagaland50.gif",
  "nagaland55.gif",
  "odisha17.gif",
  "odisha19.gif",
  "odisha23.gif",
  "odisha50.gif",
  "odisha55.gif",
  "penjab17.gif",
  "penjab19.gif",
  "penjab23.gif",
  "penjab50.gif",
  "penjab55.gif",
  "penjab89.gif",
  "pondichery17.gif",
  "pondichery19.gif",
  "pondichery23.gif",
  "pondichery50.gif",
  "pondichery55.gif",
  "rajasthan17.gif",
  "rajasthan19.gif",
  "rajasthan23.gif",
  "rajasthan50.gif",
  "rajasthan55.gif",
  "rajasthan89.gif",
  "sikkim17.gif",
  "sikkim19.gif",
  "sikkim23.gif",
  "sikkim50.gif",
  "sikkim55.gif",
  "tamil17.gif",
  "tamil19.gif",
  "tamil23.gif",
  "tamil50.gif",
  "tamil55.gif",
  "telangana17.gif",
  "telangana19.gif",
  "telangana23.gif",
  "telangana50.gif",
  "telangana55.gif",
  "tripura17.gif",
  "tripura19.gif",
  "tripura23.gif",
  "tripura50.gif",
  "tripura55.gif",
  "uttar17.gif",
  "uttar19.gif",
  "uttar23.gif",
  "uttar50.gif",
  "uttar55.gif",
  "uttar89.gif",
  "uttarakhand17.gif",
  "uttarakhand19.gif",
  "uttarakhand23.gif",
  "uttarakhand50.gif",
  "uttarakhand55.gif",
  "uttarakhand89.gif",
  "yanam17.gif",
  "yanam19.gif",
  "yanam23.gif",
  "yanam50.gif",
];

export const guesslist = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
  "Karaikal",
  "Mahé",
  "Yanam",
];

export const correct = [
  { map: "andhra", value: 1 },
  { map: "arunachal", value: 2 },
  { map: "assam", value: 3 },
  { map: "bengale", value: 28 },
  { map: "bihar", value: 4 },
  { map: "chandigarh", value: 30 },
  { map: "chhattisgarh", value: 5 },
  { map: "dadra", value: 31 },
  { map: "delhi", value: 32 },
  { map: "goa", value: 6 },
  { map: "gujarat", value: 7 },
  { map: "haryana", value: 8 },
  { map: "himachal", value: 9 },
  { map: "jammuandkashmir", value: 33 },
  { map: "jharkhand", value: 10 },
  { map: "karaikal", value: 37 },
  { map: "karnataka", value: 11 },
  { map: "kerala", value: 12 },
  { map: "ladakh", value: 34 },
  { map: "madhya", value: 13 },
  { map: "maharashtra", value: 14 },
  { map: "mahe", value: 38 },
  { map: "manipur", value: 15 },
  { map: "meghalaya", value: 16 },
  { map: "mizoram", value: 17 },
  { map: "nagaland", value: 18 },
  { map: "odisha", value: 19 },
  { map: "penjab", value: 20 },
  { map: "pondichery", value: 36 },
  { map: "rajasthan", value: 21 },
  { map: "sikkim", value: 22 },
  { map: "tamil", value: 23 },
  { map: "telangana", value: 24 },
  { map: "tripura", value: 25 },
  { map: "uttar", value: 26 },
  { map: "uttarakhand", value: 27 },
  { map: "yanam", value: 39 },
];
